title: Page by Page API Documentation
description: Track progress, capture thoughts. One page at a time.
show_downloads: false
remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme
